import {MigrationInterface, QueryRunner} from "typeorm";

export class CFChannelMultistore1654553335736 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "temporary_product" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "enabled" boolean NOT NULL DEFAULT (1), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "featuredAssetId" integer, CONSTRAINT "FK_91a19e6613534949a4ce6e76ff8" FOREIGN KEY ("featuredAssetId") REFERENCES "asset" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_product"("createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId") SELECT "createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId" FROM "product"`, undefined);
        await queryRunner.query(`DROP TABLE "product"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_product" RENAME TO "product"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_channel" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "code" varchar NOT NULL, "token" varchar NOT NULL, "defaultLanguageCode" varchar NOT NULL, "currencyCode" varchar NOT NULL, "pricesIncludeTax" boolean NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "defaultTaxZoneId" integer, "defaultShippingZoneId" integer, "logoId" integer, "customFieldsDisplayname" varchar(255), "customFieldsSubdomain" varchar(255), "customFieldsDeployedurl" varchar(255), "customFieldsPrimarycolor" varchar(7), "customFieldsSecondarycolor" varchar(255), CONSTRAINT "UQ_842699fce4f3470a7d06d89de88" UNIQUE ("token"), CONSTRAINT "UQ_06127ac6c6d913f4320759971db" UNIQUE ("code"), CONSTRAINT "FK_c9ca2f58d4517460435cbd8b4c9" FOREIGN KEY ("defaultShippingZoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_afe9f917a1c82b9e9e69f7c6129" FOREIGN KEY ("defaultTaxZoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_channel"("createdAt", "updatedAt", "code", "token", "defaultLanguageCode", "currencyCode", "pricesIncludeTax", "id", "defaultTaxZoneId", "defaultShippingZoneId") SELECT "createdAt", "updatedAt", "code", "token", "defaultLanguageCode", "currencyCode", "pricesIncludeTax", "id", "defaultTaxZoneId", "defaultShippingZoneId" FROM "channel"`, undefined);
        await queryRunner.query(`DROP TABLE "channel"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_channel" RENAME TO "channel"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_channel" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "code" varchar NOT NULL, "token" varchar NOT NULL, "defaultLanguageCode" varchar NOT NULL, "currencyCode" varchar NOT NULL, "pricesIncludeTax" boolean NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "defaultTaxZoneId" integer, "defaultShippingZoneId" integer, "logoId" integer, "customFieldsDisplayname" varchar(255), "customFieldsSubdomain" varchar(255), "customFieldsDeployedurl" varchar(255), "customFieldsPrimarycolor" varchar(7), "customFieldsSecondarycolor" varchar(255), CONSTRAINT "UQ_842699fce4f3470a7d06d89de88" UNIQUE ("token"), CONSTRAINT "UQ_06127ac6c6d913f4320759971db" UNIQUE ("code"), CONSTRAINT "FK_c9ca2f58d4517460435cbd8b4c9" FOREIGN KEY ("defaultShippingZoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_afe9f917a1c82b9e9e69f7c6129" FOREIGN KEY ("defaultTaxZoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d4709364b2fb8a69c6f6e1222ae" FOREIGN KEY ("logoId") REFERENCES "asset" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_channel"("createdAt", "updatedAt", "code", "token", "defaultLanguageCode", "currencyCode", "pricesIncludeTax", "id", "defaultTaxZoneId", "defaultShippingZoneId", "logoId", "customFieldsDisplayname", "customFieldsSubdomain", "customFieldsDeployedurl", "customFieldsPrimarycolor", "customFieldsSecondarycolor") SELECT "createdAt", "updatedAt", "code", "token", "defaultLanguageCode", "currencyCode", "pricesIncludeTax", "id", "defaultTaxZoneId", "defaultShippingZoneId", "logoId", "customFieldsDisplayname", "customFieldsSubdomain", "customFieldsDeployedurl", "customFieldsPrimarycolor", "customFieldsSecondarycolor" FROM "channel"`, undefined);
        await queryRunner.query(`DROP TABLE "channel"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_channel" RENAME TO "channel"`, undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "channel" RENAME TO "temporary_channel"`, undefined);
        await queryRunner.query(`CREATE TABLE "channel" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "code" varchar NOT NULL, "token" varchar NOT NULL, "defaultLanguageCode" varchar NOT NULL, "currencyCode" varchar NOT NULL, "pricesIncludeTax" boolean NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "defaultTaxZoneId" integer, "defaultShippingZoneId" integer, "logoId" integer, "customFieldsDisplayname" varchar(255), "customFieldsSubdomain" varchar(255), "customFieldsDeployedurl" varchar(255), "customFieldsPrimarycolor" varchar(7), "customFieldsSecondarycolor" varchar(255), CONSTRAINT "UQ_842699fce4f3470a7d06d89de88" UNIQUE ("token"), CONSTRAINT "UQ_06127ac6c6d913f4320759971db" UNIQUE ("code"), CONSTRAINT "FK_c9ca2f58d4517460435cbd8b4c9" FOREIGN KEY ("defaultShippingZoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_afe9f917a1c82b9e9e69f7c6129" FOREIGN KEY ("defaultTaxZoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "channel"("createdAt", "updatedAt", "code", "token", "defaultLanguageCode", "currencyCode", "pricesIncludeTax", "id", "defaultTaxZoneId", "defaultShippingZoneId", "logoId", "customFieldsDisplayname", "customFieldsSubdomain", "customFieldsDeployedurl", "customFieldsPrimarycolor", "customFieldsSecondarycolor") SELECT "createdAt", "updatedAt", "code", "token", "defaultLanguageCode", "currencyCode", "pricesIncludeTax", "id", "defaultTaxZoneId", "defaultShippingZoneId", "logoId", "customFieldsDisplayname", "customFieldsSubdomain", "customFieldsDeployedurl", "customFieldsPrimarycolor", "customFieldsSecondarycolor" FROM "temporary_channel"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_channel"`, undefined);
        await queryRunner.query(`ALTER TABLE "channel" RENAME TO "temporary_channel"`, undefined);
        await queryRunner.query(`CREATE TABLE "channel" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "code" varchar NOT NULL, "token" varchar NOT NULL, "defaultLanguageCode" varchar NOT NULL, "currencyCode" varchar NOT NULL, "pricesIncludeTax" boolean NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "defaultTaxZoneId" integer, "defaultShippingZoneId" integer, CONSTRAINT "UQ_842699fce4f3470a7d06d89de88" UNIQUE ("token"), CONSTRAINT "UQ_06127ac6c6d913f4320759971db" UNIQUE ("code"), CONSTRAINT "FK_c9ca2f58d4517460435cbd8b4c9" FOREIGN KEY ("defaultShippingZoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_afe9f917a1c82b9e9e69f7c6129" FOREIGN KEY ("defaultTaxZoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "channel"("createdAt", "updatedAt", "code", "token", "defaultLanguageCode", "currencyCode", "pricesIncludeTax", "id", "defaultTaxZoneId", "defaultShippingZoneId") SELECT "createdAt", "updatedAt", "code", "token", "defaultLanguageCode", "currencyCode", "pricesIncludeTax", "id", "defaultTaxZoneId", "defaultShippingZoneId" FROM "temporary_channel"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_channel"`, undefined);
        await queryRunner.query(`ALTER TABLE "product" RENAME TO "temporary_product"`, undefined);
        await queryRunner.query(`CREATE TABLE "product" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "enabled" boolean NOT NULL DEFAULT (1), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "featuredAssetId" integer, "customFieldsInfourl" varchar(255), CONSTRAINT "FK_91a19e6613534949a4ce6e76ff8" FOREIGN KEY ("featuredAssetId") REFERENCES "asset" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "product"("createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId") SELECT "createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId" FROM "temporary_product"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_product"`, undefined);
   }

}
